server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_edu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: password

  #nocas端口号
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #设置返回的json的时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    #redis配置
    #spring.redis.host=(192.168.44.132)redis地址
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/flyedu/mapper/xml/*Mapper.xml
  type-aliases-package: com.flyblog.entity
  #mybatis日志
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#开启熔断机制
feign:
  hystrix:
    enabled: true

#超时时间（默认为1000m）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds=3000:

#设置日志级别
logging:
  level:
    root: info



